/**
 * 15 Complete Songs Dataset with Timestamped Lyrics, HD Photos & Audio Files
 */

const SONGS_DATA = [
  {
    id: "starboy",
    title: "Starboy",
    album: "Starboy (2016)",
    language: "English",
    sungBy: "The Weeknd ft. Daft Punk",
    lyricsBy: "Abel Tesfaye, Guy-Manuel de Homem-Christo, Thomas Bangalter, Martin McKinney",
    musicBy: "Daft Punk, Doc McKinney, Cirkut, The Weeknd",
    duration: "3:50",
    durationSec: 230,
    cover: "images/cover_starboy.jpg",
    audioSrc: "audio/starboy.mp3",
    themeColor: "#e60026",
    badge: "GLOBAL HIT",
    mood: "Dark Pop / R&B",
    timedLyrics: [
      { time: 0, text: "[Intro]" },
      { time: 14, text: "Ayy" },
      { time: 17, text: "I'm tryna put you in the worst mood, ah" },
      { time: 21, text: "P1 cleaner than your church shoes, ah" },
      { time: 25, text: "Milli point two just to hurt you, ah" },
      { time: 29, text: "All red Lamb' just to tease you, ah" },
      { time: 33, text: "None of these toys on lease too, ah" },
      { time: 37, text: "Made your whole year in a week too, yeah" },
      { time: 41, text: "Main bitch outta your league too, ah" },
      { time: 45, text: "Side bitch outta your league too, ah" },
      { time: 49, text: "[Pre-Chorus]" },
      { time: 50, text: "House so empty, need a centerpiece" },
      { time: 54, text: "Twenty racks a table, cut from ebony" },
      { time: 58, text: "Cut that ivory into skinny pieces" },
      { time: 62, text: "Then she clean it with her face, man, I love my baby, ah" },
      { time: 66, text: "You talkin' money, need a hearing aid" },
      { time: 70, text: "You talkin' 'bout me, I don't see the shade" },
      { time: 74, text: "Switch up my style, I take any lane" },
      { time: 78, text: "I switch up my cup, I kill any pain" },
      { time: 81, text: "[Chorus]" },
      { time: 82, text: "Look what you've done" },
      { time: 85, text: "(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)" },
      { time: 89, text: "I'm a motherfuckin' starboy" },
      { time: 93, text: "(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)" },
      { time: 97, text: "Look what you've done" },
      { time: 101, text: "(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)" },
      { time: 105, text: "I'm a motherfuckin' starboy" },
      { time: 110, text: "[Verse 2]" },
      { time: 112, text: "Every day a nigga try to test me, ah" },
      { time: 116, text: "Every day a nigga try to end me, ah" },
      { time: 120, text: "Pull up in the Roadster SV, ah" },
      { time: 124, text: "Pockets overweight, gettin' hefty, ah" },
      { time: 128, text: "Coming for the king, that's a far cry, ah" },
      { time: 132, text: "I come alive in the fall time, I" },
      { time: 136, text: "No competition, don't gotta die" },
      { time: 140, text: "I'm in the blue Mulsanne bumping New Edition" },
      { time: 144, text: "[Pre-Chorus]" },
      { time: 146, text: "House so empty, need a centerpiece" },
      { time: 150, text: "Twenty racks a table, cut from ebony" },
      { time: 154, text: "Cut that ivory into skinny pieces" },
      { time: 158, text: "Then she clean it with her face, man, I love my baby, ah" },
      { time: 162, text: "You talkin' money, need a hearing aid" },
      { time: 166, text: "You talkin' 'bout me, I don't see the shade" },
      { time: 170, text: "Switch up my style, I take any lane" },
      { time: 174, text: "I switch up my cup, I kill any pain" },
      { time: 177, text: "[Chorus]" },
      { time: 178, text: "Look what you've done" },
      { time: 182, text: "(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)" },
      { time: 186, text: "I'm a motherfuckin' starboy" },
      { time: 190, text: "(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)" },
      { time: 194, text: "Look what you've done" },
      { time: 198, text: "(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)" },
      { time: 202, text: "I'm a motherfuckin' starboy" }
    ]
  },
  {
    id: "massa-massa",
    title: "Massa Massa",
    album: "Peddi (2026)",
    language: "Telugu",
    sungBy: "Vishal Mishra",
    lyricsBy: "Anantha Sriram",
    musicBy: "A. R. Rahman",
    duration: "3:42",
    durationSec: 222,
    cover: "images/cover_massa.jpg",
    audioSrc: "audio/massa-massa.m4a",
    themeColor: "#ff7b00",
    badge: "TRENDING MASS",
    mood: "Folk Energy / Dance",
    timedLyrics: [
      { time: 0, text: "[Pallavi - Mass Intro]" },
      { time: 14, text: "Hey massa massa massu koraa" },
      { time: 24, text: "Peddi entry choosi loku dharu maaru raa" },
      { time: 34, text: "Gundello dharuvu kottu dholu vaayinchu raa" },
      { time: 44, text: "Nela thalliki dandam petti arupulu theeyyaraa!" },
      { time: 54, text: "Massa massa massa massa" },
      { time: 64, text: "Dhummu dhoolu lechipovaala" },
      { time: 74, text: "Massa massa massa massa" },
      { time: 84, text: "Akkada ikkada anthaa mana thopaala" },
      { time: 94, text: "[Charanam 1]" },
      { time: 96, text: "Kallalona nippu undhi" },
      { time: 106, text: "Kaalla kinda boomi undhi" },
      { time: 116, text: "Meesam thippina magaadocchindu" },
      { time: 126, text: "Daawat chesukoraa pillaa!" },
      { time: 136, text: "[Chorus]" },
      { time: 138, text: "Massa massa mass amma" },
      { time: 148, text: "Massu koraa peddammma" },
      { time: 158, text: "Janta katti aadindante" },
      { time: 168, text: "Rangam mottham maari povaala!" }
    ]
  },
  {
    id: "laila-o-laila",
    title: "Laila O Laila",
    album: "Raees (2017)",
    language: "Hindi",
    sungBy: "Pawni Pandey",
    lyricsBy: "Indeevar, Javed Akhtar",
    musicBy: "Kalyanji - Anandji, Ram Sampath",
    duration: "3:38",
    durationSec: 218,
    cover: "images/cover_laila.jpg",
    audioSrc: "audio/laila-o-laila.mp3",
    themeColor: "#e91e63",
    badge: "CLUB DANCE",
    mood: "Electrifying Retro",
    timedLyrics: [
      { time: 0, text: "[Intro]" },
      { time: 12, text: "Laila... O Laila..." },
      { time: 22, text: "Laila main laila, aisi hoon laila" },
      { time: 30, text: "Har koi chaahe mujhse milna akela" },
      { time: 39, text: "Laila main laila, aisi hoon laila" },
      { time: 48, text: "Har koi chaahe mujhse milna akela" },
      { time: 56, text: "Jisko bhi dekhun deewana kar doon" },
      { time: 65, text: "Laila o laila aisi main laila" },
      { time: 75, text: "[Verse 1]" },
      { time: 76, text: "Mohabbat ka jisko tareeqa na aaya" },
      { time: 86, text: "Use zindagani ka daawa na aaya" },
      { time: 96, text: "Kareeb aa ke dekho zara mere dilbar" },
      { time: 106, text: "Ye jaadoo hamare siva kisko aaya" },
      { time: 116, text: "[Chorus]" },
      { time: 118, text: "Laila main laila, aisi hoon laila" },
      { time: 128, text: "Har koi chaahe mujhse milna akela" },
      { time: 138, text: "O laila! Tere naina churaaye mera chain" },
      { time: 148, text: "O laila! Teri baatein badhaaye meri pyaas" }
    ]
  },
  {
    id: "oo-antava",
    title: "Oo Antava Oo Oo Antava",
    album: "Pushpa: The Rise (2021)",
    language: "Telugu",
    sungBy: "Indravathi Chauhan",
    lyricsBy: "Chandrabose",
    musicBy: "Devi Sri Prasad (DSP)",
    duration: "3:44",
    durationSec: 224,
    cover: "images/cover_ooantava.jpg",
    audioSrc: "audio/oo-antava.m4a",
    themeColor: "#ff0055",
    badge: "SENSATION",
    mood: "Groovy / Hypnotic",
    timedLyrics: [
      { time: 0, text: "[Pallavi - Intro]" },
      { time: 12, text: "Koka koka kaddithey korukku thintaaru" },
      { time: 22, text: "Pavada kattithey paitham chuupisthaaru" },
      { time: 32, text: "Koka kaadhu pavada kaadhu kattubatte kaadhu" },
      { time: 42, text: "Mee magabudhey vankara budhi" },
      { time: 52, text: "Oo antava mava.. Oo oo antava mava!" },
      { time: 62, text: "Oo antava mava.. Oo oo antava mava!" },
      { time: 74, text: "[Charanam 1]" },
      { time: 76, text: "Tella tellaga unte okallu" },
      { time: 86, text: "Nallanallaga unte inkokallu" },
      { time: 96, text: "Chubbu chuupultho pichekkinchi" },
      { time: 106, text: "Valavesi laagesthaaru" },
      { time: 116, text: "[Chorus]" },
      { time: 118, text: "Mee magajaathi antha anthe" },
      { time: 128, text: "Mee gunde lothu maku theluse" },
      { time: 138, text: "Oo antava mava.. Oo oo antava mava!" },
      { time: 148, text: "Oo antava mava.. Oo oo antava mava!" }
    ]
  },
  {
    id: "underrated",
    title: "Underrated",
    album: "Dino James - The Hustle",
    language: "Hindi",
    sungBy: "Dino James",
    lyricsBy: "Dino James",
    musicBy: "Dino James, Bluish Music",
    duration: "3:55",
    durationSec: 235,
    cover: "images/cover_underrated.jpg",
    audioSrc: "audio/underrated.m4a",
    themeColor: "#00e5ff",
    badge: "DESI HIP-HOP",
    mood: "Raw / Motivational",
    timedLyrics: [
      { time: 0, text: "[Intro 808 Beat]" },
      { time: 10, text: "Poori life laake rakh di maine sabke saamne" },
      { time: 20, text: "Toote sapno ko saare maine liye kaam mein" },
      { time: 30, text: "Underrated aur tha underdog mein" },
      { time: 40, text: "Bulaya nahi kisi ne par hoon aamne-saamne!" },
      { time: 50, text: "Maine kabhi nahi maangi kisi se bhi reham" },
      { time: 60, text: "Mujhe pata tha ki khuda mere saath hai hardam" },
      { time: 72, text: "Har ek haar se maine seekha naya sabak" },
      { time: 84, text: "Ab jo bhi main bolun usme rehta hai alag chamak" },
      { time: 96, text: "[Hook]" },
      { time: 98, text: "Kaam bolega mera, main nahi bolunga" },
      { time: 110, text: "Band darwaze saare mehnat se kholunga" },
      { time: 122, text: "Likh ke le le beta ruka nahi hoon main" },
      { time: 134, text: "Aandhiyon ke aage bhi jhuka nahi hoon main" }
    ]
  },
  {
    id: "sao-paulo",
    title: "São Paulo",
    album: "Hurry Up Tomorrow (2024)",
    language: "English",
    sungBy: "The Weeknd ft. Anitta",
    lyricsBy: "Abel Tesfaye, Larissa Machado (Anitta), Mike Dean",
    musicBy: "The Weeknd, Mike Dean",
    duration: "3:40",
    durationSec: 220,
    cover: "images/cover_saopaulo.jpg",
    audioSrc: "audio/sao-paulo.m4a",
    themeColor: "#9c27b0",
    badge: "GLOBAL VIBE",
    mood: "Baile Funk / Dark Synth",
    timedLyrics: [
      { time: 0, text: "[Intro - Dark Synth]" },
      { time: 12, text: "São Paulo nights, city lights shine bright" },
      { time: 22, text: "Move to the rhythm till the morning light" },
      { time: 32, text: "You know I want it, you know I need it" },
      { time: 42, text: "Feel the heat rising through the concrete" },
      { time: 54, text: "[Chorus - Anitta]" },
      { time: 56, text: "Corpo suado no ritmo do tambor" },
      { time: 68, text: "Essa noite a gente vai fazer amor" },
      { time: 80, text: "Vem dançar comigo nessa loucura" },
      { time: 92, text: "A batida é forte e não tem censura" },
      { time: 104, text: "[Verse 2]" },
      { time: 106, text: "Feel the bass dropping low in the street" },
      { time: 118, text: "São Paulo rhythm taking over your feet" },
      { time: 130, text: "Under neon skies we lose all control" }
    ]
  },
  {
    id: "bulleya",
    title: "Bulleya",
    album: "Ae Dil Hai Mushkil (2016)",
    language: "Hindi",
    sungBy: "Amit Mishra, Shilpa Rao",
    lyricsBy: "Amitabh Bhattacharya",
    musicBy: "Pritam",
    duration: "5:49",
    durationSec: 349,
    cover: "images/cover_bulleya.jpg",
    audioSrc: "audio/bulleya.mp3",
    themeColor: "#d32f2f",
    badge: "SUFI ROCK",
    mood: "Intense / Passionate",
    timedLyrics: [
      { time: 0, text: "[Intro Alap - Shilpa Rao]" },
      { time: 16, text: "Meri rooh ka parinda phadphadaaye" },
      { time: 26, text: "Lekin sukoon ka jazeera mil na paaye" },
      { time: 36, text: "Ve ki karaan, ve ki karaan" },
      { time: 47, text: "[Verse 1 - Amit Mishra]" },
      { time: 49, text: "Ik baar ko tajalli toh dikha de" },
      { time: 59, text: "Jhoothi sahi magar tasalli toh dila de" },
      { time: 69, text: "Ve ki karaan, ve ki karaan" },
      { time: 79, text: "[Pre-Chorus]" },
      { time: 81, text: "Ranjhana ve.. Ranjhana ve.." },
      { time: 91, text: "Raanjhana ve.. Ranjhana ve.." },
      { time: 101, text: "[Chorus]" },
      { time: 103, text: "Yeh fitoor mera laaye mujhko tere kareeb" },
      { time: 113, text: "Kyun bewajah sa lage ishq ka yeh ajeeb naseeb" },
      { time: 123, text: "Bulleya ki jaana main kaun" },
      { time: 133, text: "Bulleya ki jaana main kaun" },
      { time: 145, text: "Tu firaaq hai ya visaal hai" },
      { time: 155, text: "Tu hi dard hai tu malaal hai" },
      { time: 167, text: "Bulleya parwardigaar ve!" }
    ]
  },
  {
    id: "yesu-nagula",
    title: "Yesu Nagula Gada Meeda",
    album: "The Paradise (2026)",
    language: "Telugu",
    sungBy: "Anirudh Ravichander, Mass Folk Troupe",
    lyricsBy: "Kasarla Shyam",
    musicBy: "Anirudh Ravichander",
    duration: "3:35",
    durationSec: 215,
    cover: "images/cover_yesunagula.jpg",
    audioSrc: "audio/yesu-nagula.m4a",
    themeColor: "#ff9800",
    badge: "VIRAL FOLK",
    mood: "High Energy Teenmaar",
    timedLyrics: [
      { time: 0, text: "[Pallavi - Mass Teenmaar]" },
      { time: 12, text: "Yesu nagula gada meeda rechipoyina daawat choodu" },
      { time: 24, text: "Teenmaar beatuki kottara dholu" },
      { time: 36, text: "Gadda meeda mass thalaivaru vacche" },
      { time: 48, text: "Dhummu lechipoye arupulu choode!" },
      { time: 60, text: "[Charanam 1]" },
      { time: 62, text: "Oorantha okate jathara" },
      { time: 74, text: "Kaallu nilavakunda aadu bey joraa" },
      { time: 86, text: "Kattu bongi thoti kottedhi rhythm" },
      { time: 98, text: "Manatho pettukunte jarigedhi yuddham!" },
      { time: 110, text: "[Chorus]" },
      { time: 112, text: "Gadda meeda rangam sidham" },
      { time: 124, text: "Yesu nagula gada meeda dhummu lepey raa!" }
    ]
  },
  {
    id: "aya-sher",
    title: "Aya Sher (Jumbalikay)",
    album: "The Paradise (2026)",
    language: "Telugu",
    sungBy: "Addula Jangireddy, Arjun Chandy",
    lyricsBy: "Kasarla Shyam",
    musicBy: "Anirudh Ravichander",
    duration: "3:25",
    durationSec: 205,
    cover: "images/cover_ayasher.jpg",
    audioSrc: "audio/aya-sher.m4a",
    themeColor: "#fbc02d",
    badge: "ROARING MASS",
    mood: "Fierce Tribal Beat",
    timedLyrics: [
      { time: 0, text: "[Pallavi - Tribal Roar]" },
      { time: 10, text: "Hey nee ayya jagiraa" },
      { time: 20, text: "Chal maavaadochindra, iga jadthiyyaley" },
      { time: 30, text: "Jumbalikay aaya sher!" },
      { time: 42, text: "Hey aa daar kaa sulthaane" },
      { time: 52, text: "Maa ghar kaa saithaane" },
      { time: 64, text: "Chal shikaar jeyya, jumbalikay aaya sher!" },
      { time: 76, text: "[Charanam]" },
      { time: 78, text: "Dhadadhada gundelu badhithe" },
      { time: 90, text: "Arupulu aakasam thakithe" },
      { time: 102, text: "Mogipoye nagaraa soundu" },
      { time: 114, text: "Jumbalikay aaya sher!" }
    ]
  },
  {
    id: "rai-rai-raa-raa",
    title: "Rai Rai Raa Raa",
    album: "Peddi (2026)",
    language: "Telugu",
    sungBy: "A. R. Rahman",
    lyricsBy: "Anantha Sriram",
    musicBy: "A. R. Rahman",
    duration: "4:12",
    durationSec: 252,
    cover: "images/cover_rairai.jpg",
    audioSrc: "audio/rai-rai-raa-raa.m4a",
    themeColor: "#ff5722",
    badge: "POWER ANTHEM",
    mood: "Motivational / Epic",
    timedLyrics: [
      { time: 0, text: "[Pallavi - Epic Brass]" },
      { time: 14, text: "Rai rai raa raa, rai rai raa raa" },
      { time: 26, text: "Adde leni dhaarai raa raa" },
      { time: 38, text: "Rai rai raa raa, rai rai raa raa" },
      { time: 50, text: "Hadde leni thirai raa raa" },
      { time: 64, text: "[Charanam 1]" },
      { time: 66, text: "Thagaleti sooreedaa, tharumukoni vacchaava" },
      { time: 80, text: "Dhadadhada gunadhelalo jwalalai lechaava" },
      { time: 94, text: "Ninnu aape shakthi evariki ledhuraa" },
      { time: 108, text: "Gelupe nee paadam mundhu vaaluthundhiraa!" },
      { time: 122, text: "Kaalaanne thiragesi charithra raayaraa!" }
    ]
  },
  {
    id: "ye-tune-kya-kiya",
    title: "Ye Tune Kya Kiya",
    album: "Once Upon A Time In Mumbaai Dobaara (2013)",
    language: "Hindi",
    sungBy: "Javed Bashir",
    lyricsBy: "Rajat Arora",
    musicBy: "Pritam",
    duration: "5:14",
    durationSec: 314,
    cover: "images/cover_yetune.jpg",
    audioSrc: "audio/ye-tune-kya-kiya.m4a",
    themeColor: "#673ab7",
    badge: "SOULFUL CLASSIC",
    mood: "Qawwali / Romantic",
    timedLyrics: [
      { time: 0, text: "[Intro Qawwali]" },
      { time: 15, text: "Ishq wo bala hai, ishq wo bala hai" },
      { time: 28, text: "Jisko chhua isne wo jala hai" },
      { time: 42, text: "Dil se hota hai shuru, par kambakht sar pe chadhta hai" },
      { time: 56, text: "Kabhi khud pe, kabhi rab pe, har baat pe ladta hai" },
      { time: 70, text: "[Chorus]" },
      { time: 72, text: "Ye tune kya kiya, khuda hi jaane" },
      { time: 86, text: "Kyun tere aage main jhukne laga hoon" },
      { time: 100, text: "Ye tune kya kiya, khuda hi jaane" },
      { time: 114, text: "Kyun tere khwaabon mein behne laga hoon" },
      { time: 128, text: "Har qatra mera ab tera hua" },
      { time: 142, text: "Meri saari duayein tere naam hua" }
    ]
  },
  {
    id: "channa-mereya",
    title: "Channa Mereya",
    album: "Ae Dil Hai Mushkil (2016)",
    language: "Hindi",
    sungBy: "Arijit Singh",
    lyricsBy: "Amitabh Bhattacharya",
    musicBy: "Pritam",
    duration: "4:49",
    durationSec: 289,
    cover: "images/cover_channa.jpg",
    audioSrc: "audio/channa-mereya.mp3",
    themeColor: "#ffb300",
    badge: "HEARTBREAK ANTHEM",
    mood: "Melancholy / Acoustic",
    timedLyrics: [
      { time: 0, text: "[Intro Acoustic Guitar]" },
      { time: 13, text: "Accha chalta hoon, duaon mein yaad rakhna" },
      { time: 24, text: "Mere zikr ka zubaan pe swaad rakhna" },
      { time: 36, text: "Dil ke sandookon mein mere acche kaam rakhna" },
      { time: 47, text: "Chitthi taaron mein bhi mera tu salaam rakhna" },
      { time: 59, text: "[Pre-Chorus]" },
      { time: 61, text: "Andhera tera maine le liya" },
      { time: 70, text: "Mera ujla sitaara tere naam kiya" },
      { time: 79, text: "[Chorus]" },
      { time: 81, text: "Channa mereya mereya, channa mereya mereya" },
      { time: 91, text: "Channa mereya mereya beliya, o piya.." },
      { time: 101, text: "Channa mereya mereya, channa mereya mereya" },
      { time: 112, text: "Channa mereya mereya beliya, o piya.." },
      { time: 124, text: "[Verse 2]" },
      { time: 126, text: "Mehfil mein teri hum naa rahe jo" },
      { time: 136, text: "Gham toh nahi hai, gham toh nahi hai" },
      { time: 147, text: "Qisse humaare nazdeeqiyon ke" },
      { time: 157, text: "Kam toh nahi hai, kam toh nahi hai" },
      { time: 169, text: "Channa mereya mereya beliya, o piya!" }
    ]
  },
  {
    id: "trance-of-omi",
    title: "Trance of Omi",
    album: "Bheemla Nayak / OG (2022)",
    language: "Telugu",
    sungBy: "Sri Krishna, Prudhvi Chandra",
    lyricsBy: "Ramajogayya Sastry",
    musicBy: "Thaman S",
    duration: "3:10",
    durationSec: 190,
    cover: "images/cover_omi.jpg",
    audioSrc: "audio/trance-of-omi.m4a",
    themeColor: "#00b0ff",
    badge: "MASS TRANCE",
    mood: "Electric / Heavy Bass",
    timedLyrics: [
      { time: 0, text: "[Pallavi - Heavy Synth]" },
      { time: 12, text: "Nippulanti kalla choodu" },
      { time: 24, text: "Naralalo currentoodu" },
      { time: 36, text: "Simhamanti manishi vacche" },
      { time: 48, text: "Omi ani pilusthaaru!" },
      { time: 60, text: "[Charanam]" },
      { time: 62, text: "Trance of fire, trance of power" },
      { time: 76, text: "Agni kundamlo udayinchina sooryudu veedu" },
      { time: 90, text: "Vennupusa vanikipoye shatruvu mundhu" },
      { time: 104, text: "Omi.. Trance of Omi!" },
      { time: 118, text: "Dhandayatra modalayyindhi, kotta raa dharuvu!" }
    ]
  },
  {
    id: "ogas-gambhira",
    title: "Ojas Gambhira (Hungry Cheetah)",
    album: "OG - They Call Him OG (2025)",
    language: "Telugu",
    sungBy: "Thaman S, Chorus",
    lyricsBy: "Kalyan Chakravarthy",
    musicBy: "Thaman S",
    duration: "3:30",
    durationSec: 210,
    cover: "images/cover_og.jpg",
    audioSrc: "audio/ogas-gambhira.m4a",
    themeColor: "#ff1744",
    badge: "BLOCKBUSTER ROAR",
    mood: "Dark Mafia / Cinematic",
    timedLyrics: [
      { time: 0, text: "[Intro - Cinematic Roar]" },
      { time: 12, text: "Ojas Gambhira!" },
      { time: 22, text: "Storm is coming, blood is boiling" },
      { time: 34, text: "The predator has arrived in Bombay!" },
      { time: 46, text: "Ojas gambhira gonthe vinte bhookampam" },
      { time: 58, text: "Choope chalu shatruvuku maranam" },
      { time: 72, text: "Hungry cheetah running in the wild" },
      { time: 84, text: "Fire in his eyes, storm in his stride!" },
      { time: 98, text: "[Chorus]" },
      { time: 100, text: "They call him OG!" },
      { time: 112, text: "Nippula varsham kurisela, narakadam veedi style-u!" }
    ]
  },
  {
    id: "nuvvu-nenantu",
    title: "Nuvvu Nenantu",
    album: "Orange (2010)",
    language: "Telugu",
    sungBy: "KK (Krishnakumar Kunnath)",
    lyricsBy: "Vanamali",
    musicBy: "Harris Jayaraj",
    duration: "4:32",
    durationSec: 272,
    cover: "images/cover_orange.jpg",
    audioSrc: "audio/nuvvu-nenantu.m4a",
    themeColor: "#00e676",
    badge: "EVERGREEN MELODY",
    mood: "Romantic / Nostalgic",
    timedLyrics: [
      { time: 0, text: "[Pallavi - Guitar Intro]" },
      { time: 14, text: "Nuvvu nenantu unte preme kadha" },
      { time: 26, text: "Gunde lo daachukunte mounam kadha" },
      { time: 38, text: "Kaliseti kshaname edho varam" },
      { time: 50, text: "Vidipoye roje edho ghaayam" },
      { time: 64, text: "[Charanam 1]" },
      { time: 66, text: "Ee praanam neetho unte chaley" },
      { time: 78, text: "Naa oohallo nuvve unte chaley" },
      { time: 90, text: "Ekkadiko theliyani dhaarilo" },
      { time: 102, text: "Neetho nadavatam oka paravasam" },
      { time: 114, text: "Vennela kaase vela manasu, nee prematho nindi ponu!" }
    ]
  }
];

// Attach full plain text lyrics property to each song for quick reading and copying
SONGS_DATA.forEach(song => {
  song.lyrics = song.timedLyrics.map(line => line.text).join("\n");
});
